language: python

Python:
- "2.7"
- "3.6"


install:
-pip install -r requirements.txt
-pip install pytest
`
script:
`
-- coverage run  --source tests/api/v1 -m pytest -v

after_success:
-coveralls
