language: python

Python:
- "2.7"
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install nose

script:
- nosetests --with-coverage --cover-package=app test_views.py

after_success:
-"coveralls"
