language: python

Python:
- "3.6"
install:
- pip install -r requirment.txt
- pip install coveralls
- pip install nose

script:
- nosetests --with-coverage --cover-package=.

after_success:
-"coveralls"
