language: python

Python:
- "2.7"
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install nose

script:
python test_views.py --with-coverage --cover-package=app 

after_success:
-"coveralls"
